import { Color } from "./Color";

export const CONTROLSHIDETIME = 3000;
export const INITIALCONFIGURATION = {
  BUTTONCOLOR: Color.COLORBASE,
  VolumeBar: {
    BACKGROUNDCOLOR: Color.COLORBASE,
    VOLUMECOLOR: Color.TURQUOUSE,
    CONTAINERCOLOR: Color.LIGHTGRAY,
    THUMBCOLOR: Color.GREEN,
  },
  ProgressBar: {
    BUFFEREDCOLOR: Color.BUFFERED_COLOR,
    BACKGROUNDCOLOR: Color.BACKGROUND_COLORBASE,
    PROGRESSCOLOR: Color.TURQUOUSE,
    THUMBCOLOR: Color.GREEN,
    TEXT: Color.COLORBASE,
  },
  Time: {
    COLOR: Color.COLORBASE,
  },
  QualitySelector: {
    BACKGROUND: Color.COLORBASE,
    TEXTCOLOR: {
      PRIMARY: Color.BLACK,
      SELECTED: Color.LIGHTBLACK,
    },
    BORDERCOLOR: Color.LIGHTBLUE,
    HOVER: {
      BACKGROUND: Color.HOVER_BACKGROUND,
      COLOR: Color.BLACK,
    },
  },
};
